

package com.kitakkun.fusio.compiler.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.fusio.compiler.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("fusio-compiler-plugin-tests/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FusioJvmDiagnosticTestGenerated extends AbstractFusioJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("fusio-compiler-plugin-tests/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("eventHandlerCovered.kt")
  public void testEventHandlerCovered() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/eventHandlerCovered.kt");
  }

  @Test
  @TestMetadata("eventHandlerCoveredViaFuse.kt")
  public void testEventHandlerCoveredViaFuse() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/eventHandlerCoveredViaFuse.kt");
  }

  @Test
  @TestMetadata("eventHandlerCoveredViaParent.kt")
  public void testEventHandlerCoveredViaParent() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/eventHandlerCoveredViaParent.kt");
  }

  @Test
  @TestMetadata("mapFromPropertyNameMismatch.kt")
  public void testMapFromPropertyNameMismatch() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/mapFromPropertyNameMismatch.kt");
  }

  @Test
  @TestMetadata("mapToPropertyNameMismatch.kt")
  public void testMapToPropertyNameMismatch() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/mapToPropertyNameMismatch.kt");
  }

  @Test
  @TestMetadata("mapToPropertyTypeMismatch.kt")
  public void testMapToPropertyTypeMismatch() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/mapToPropertyTypeMismatch.kt");
  }

  @Test
  @TestMetadata("missingEffectMappings.kt")
  public void testMissingEffectMappings() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/missingEffectMappings.kt");
  }

  @Test
  @TestMetadata("missingEventHandler.kt")
  public void testMissingEventHandler() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/missingEventHandler.kt");
  }

  @Test
  @TestMetadata("missingEventMappings.kt")
  public void testMissingEventMappings() {
    runTest("fusio-compiler-plugin-tests/testData/diagnostics/missingEventMappings.kt");
  }
}
