

package com.kitakkun.aria.compiler.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.aria.compiler.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("aria-compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class AriaJvmDiagnosticTestGenerated extends AbstractAriaJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("aria-compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("mapToPropertyNameMismatch.kt")
  public void testMapToPropertyNameMismatch() {
    runTest("aria-compiler-plugin/testData/diagnostics/mapToPropertyNameMismatch.kt");
  }
}
