

package com.kitakkun.fusio.compiler.test.k24.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.fusio.compiler.test.k24.GenerateTestsK24Kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("fusio-compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FusioK24JvmDiagnosticTestGenerated extends AbstractFusioK24JvmDiagnosticTest {
  private void run(String fileName) {
    runTest("fusio-compiler-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("fusio-compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("mapFromPropertyNameMismatch.kt")
  public void testMapFromPropertyNameMismatch() {
    run("mapFromPropertyNameMismatch.kt");
  }

  @Test
  @TestMetadata("mapToPropertyNameMismatch.kt")
  public void testMapToPropertyNameMismatch() {
    run("mapToPropertyNameMismatch.kt");
  }

  @Test
  @TestMetadata("mapToPropertyTypeMismatch.kt")
  public void testMapToPropertyTypeMismatch() {
    run("mapToPropertyTypeMismatch.kt");
  }

  @Test
  @TestMetadata("missingEffectMappings.kt")
  public void testMissingEffectMappings() {
    run("missingEffectMappings.kt");
  }

  @Test
  @TestMetadata("missingEventMappings.kt")
  public void testMissingEventMappings() {
    run("missingEventMappings.kt");
  }
}
