

package com.kitakkun.fusio.compiler.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.fusio.compiler.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("fusio-compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class FusioJvmBoxTestGenerated extends AbstractFusioJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("fusio-compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("composableCompiles.kt")
  public void testComposableCompiles() {
    runTest("fusio-compiler-plugin/testData/box/composableCompiles.kt");
  }

  @Test
  @TestMetadata("dataObjectSubtype.kt")
  public void testDataObjectSubtype() {
    runTest("fusio-compiler-plugin/testData/box/dataObjectSubtype.kt");
  }

  @Test
  @TestMetadata("fusioDataClass.kt")
  public void testFusioDataClass() {
    runTest("fusio-compiler-plugin/testData/box/fusioDataClass.kt");
  }

  @Test
  @TestMetadata("mappedScopeRoundTrip.kt")
  public void testMappedScopeRoundTrip() {
    runTest("fusio-compiler-plugin/testData/box/mappedScopeRoundTrip.kt");
  }

  @Test
  @TestMetadata("nestedMappedScope.kt")
  public void testNestedMappedScope() {
    runTest("fusio-compiler-plugin/testData/box/nestedMappedScope.kt");
  }

  @Test
  @TestMetadata("siblingMappedScope.kt")
  public void testSiblingMappedScope() {
    runTest("fusio-compiler-plugin/testData/box/siblingMappedScope.kt");
  }

  @Test
  @TestMetadata("validMapToCompiles.kt")
  public void testValidMapToCompiles() {
    runTest("fusio-compiler-plugin/testData/box/validMapToCompiles.kt");
  }
}
