

package com.kitakkun.fusio.compiler.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.fusio.compiler.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("fusio-compiler-plugin-tests/k2321/testData/ir")
@TestDataPath("$PROJECT_ROOT")
public class FusioJvmIrTextTestGenerated extends AbstractFusioJvmIrTextTest {
  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("fusio-compiler-plugin-tests/k2321/testData/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("fuseRewrite.kt")
  public void testFuseRewrite() {
    runTest("fusio-compiler-plugin-tests/k2321/testData/ir/fuseRewrite.kt");
  }
}
