

package com.kitakkun.fusio.compiler.test.k24.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.fusio.compiler.test.k24.GenerateTestsK24Kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("fusio-compiler-plugin-tests/k240_beta2/testData/ir")
@TestDataPath("$PROJECT_ROOT")
public class FusioK24JvmIrTextTestGenerated extends AbstractFusioK24JvmIrTextTest {
  private void run(String fileName) {
    runTest("fusio-compiler-plugin-tests/k240_beta2/testData/ir/" + fileName);
  }

  @Test
  public void testAllFilesPresentInIr() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("fusio-compiler-plugin-tests/k240_beta2/testData/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("fuseRewrite.kt")
  public void testFuseRewrite() {
    run("fuseRewrite.kt");
  }
}
