

package com.kitakkun.fusio.compiler.test.k24.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.kitakkun.fusio.compiler.test.k24.GenerateTestsK24Kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("fusio-compiler-plugin-tests/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class FusioK24JvmBoxTestGenerated extends AbstractFusioK24JvmBoxTest {
  private void run(String fileName) {
    runTest("fusio-compiler-plugin-tests/testData/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("fusio-compiler-plugin-tests/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("composableCompiles.kt")
  public void testComposableCompiles() {
    run("composableCompiles.kt");
  }

  @Test
  @TestMetadata("dataObjectSubtype.kt")
  public void testDataObjectSubtype() {
    run("dataObjectSubtype.kt");
  }

  @Test
  @TestMetadata("fuseRoundTrip.kt")
  public void testFuseRoundTrip() {
    run("fuseRoundTrip.kt");
  }

  @Test
  @TestMetadata("nestedFuse.kt")
  public void testNestedFuse() {
    run("nestedFuse.kt");
  }

  @Test
  @TestMetadata("presentationDataClass.kt")
  public void testPresentationDataClass() {
    run("presentationDataClass.kt");
  }

  @Test
  @TestMetadata("siblingFuse.kt")
  public void testSiblingFuse() {
    run("siblingFuse.kt");
  }

  @Test
  @TestMetadata("validMapToCompiles.kt")
  public void testValidMapToCompiles() {
    run("validMapToCompiles.kt");
  }
}
